version: '2'
services:
    jhipsterproject-app:
        image: jhipsterproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterproject-mysql:3306/jhipsterproject?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterproject-mysql:
        extends:
            file: mysql.yml
            service: jhipsterproject-mysql
